### PR TITLE
update tomb dependency

### PR DESCRIPTION
**Pull request by nskaggs**
In support of https://github.com/juju/juju/pull/5956

### CODE REVIEW

**Comment by natefinch** [comment]
LGTM once you update the dependency on juju/cmd once that gets committed.

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
