### PR TITLE
Add s390x as supported arch.

### PR DESCRIPTION
**Pull request by xnox**
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

### CODE REVIEW

**Comment by xnox** [comment]
@cherylj  on it. I guess I should be running tests too! How do I do that? I'll look into docs.

**Comment by xnox** [comment]
I get
```
# github.com/juju/utils/packaging/manager_test
packaging/manager/manager_test.go:271: too few values in struct initializer
packaging/manager/utils_test.go:49: too few values in struct initializer
```

However, that's none of my doing.... Branch updated.

**Comment by cherylj** [comment]
Yeah, that looks like you need to run godeps:

go get launchpad.net/godeps
cd $GOPATH/src/launchpad.net/godeps
go install ./...
cd $GOPATH/src/github.com/juju/utils
$GOPATH/bin/godeps -u dependencies.tsv

Then try and test again.  I already tested this patch and it was fine.

**Comment by cherylj** [comment]
$$fixes-1551276$$

**Comment by cherylj** [comment]
$$merge$$

**Pull request merged**
