### PR TITLE
new package: ssh, from github.com/juju/juju/utils/ssh

### PR DESCRIPTION
**Pull request by davecheney**
new package: ssh, from github.com/juju/juju/utils/ssh

(Review request: http://reviews.vapour.ws/r/3000/)

### CODE REVIEW

**Comment by davecheney** [comment]
$$merge$$

**Comment by davecheney** [comment]
$$merge$$

**Comment by davecheney** [comment]
sscyowts3dl4wfi6e72b

**Comment by davecheney** [comment]
$$$$merge$$

**Comment by bz2** [comment]
Its the same issue all build;

# golang.org/x/crypto/ssh
../../../golang.org/x/crypto/ssh/keys.go:492: undefined: crypto.Signer

Getting tip of this doesn't work, the interfaces changed in new go versions. If this is moving to utils, there needs to be a comprehensive dependencies.tsv (not just one line as was added), and the job needs to be updated to use it.

**Comment by davecheney** [comment]
$$merge$$

**Comment by davecheney** [comment]
$$merge$$

**Comment by davecheney** [comment]
$$merge$$

This time for sure.

**Comment by davecheney** [comment]
$$merge$$

**Pull request merged**
