### PR TITLE
add sierra release

### PR DESCRIPTION
**Pull request by jamesbeedy**
Add sierra release to series.go

### CODE REVIEW

**Comment by jamesbeedy** [comment]
Fixes: Bug #1627554

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
Thanks @jamesbeedy

**Comment by mitechie** [comment]
The test failure here seems legit. @jamesbeedy I think you need to fill out the next series in the test here: 

https://github.com/juju/utils/blob/dbc08fbee4c1bcf60d65f5a523149310ece56a08/series/series_test.go#L92

Let me know if you're interested in updating and landing otherwise we'll put it on the todo.

**Comment by jamesbeedy** [comment]
@mitechie, thanks! hopefully this should do it

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
Thanks @jamesbeedy!

**Comment by fenris** [comment]
Thanks @jamesbeedy

**Pull request merged**
